version: "3"
services:
  seleniarm:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "4444:4444"
