version: "3"
services:
  seleniarm:
    image: selenium/standalone-chrome:latest 
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true      
    ports:
      - "4444:4444"
  auto_attend:
    image: 